
common:
    RUN_NAME : "SACv1_SPINUP_1_LIDAR_RNN_old_map_test_5"
    save_frequency : 10
    use_wandb : True # if you use wand b setup the config


server:
    ip : "173.179.182.4" # edi:"173.179.182.4" yann : "45.74.221.204"

worker:
    cuda : False
    localhost : True  # is the worker in the same machine that the server

trainer:
    cuda : True
    localhost : False # is the trainer in the same machine that the server



if PRAGMA_EDOUARD_YANN_CC == 2:  # Override some of these for Compute Canada
    if PRAGMA_SERVER_ON_EDOUARD_YANN == 1:  # Edouard
        MODEL_PATH_TRAINER = r"/home/yannbout/scratch/base_tmrl_edouard/data/" + (RUN_NAME + "_t.pth")
        CHECKPOINT_PATH = r"/home/yannbout/scratch/base_tmrl_edouard/data/" + RUN_NAME
        REWARD_PATH = r"/home/yannbout/scratch/base_tmrl_edouard/data/reward.pkl"
    else:  # Yann
        MODEL_PATH_TRAINER = r"/home/yannbout/scratch/base_tmrl/data/" + (RUN_NAME + "_t.pth")
        CHECKPOINT_PATH = r"/home/yannbout/scratch/base_tmrl/data/" + RUN_NAME
        REWARD_PATH = r"/home/yannbout/scratch/base_tmrl/data/reward.pkl"


